/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './frontend/routes/__root'
import { Route as IndexRouteImport } from './frontend/routes/index'
import { Route as AdminRouteImport } from './frontend/routes/admin'
import { Route as AppRouteImport } from './frontend/routes/app'
import { Route as LoginRouteImport } from './frontend/routes/login'
import { Route as SignupRouteImport } from './frontend/routes/signup'
import { Route as AppIndexRouteImport } from './frontend/routes/app.index'
import { Route as AppActivityRouteImport } from './frontend/routes/app.activity'
import { Route as AppAnalyticsRouteImport } from './frontend/routes/app.analytics'
import { Route as AppHelpRouteImport } from './frontend/routes/app.help'
import { Route as AppSettingsRouteImport } from './frontend/routes/app.settings'
import { Route as AppProjectsProjectIdRouteImport } from './frontend/routes/app.projects.$projectId'
import { Route as AppSpacesIndexRouteImport } from './frontend/routes/app.spaces.index'
import { Route as AppSpacesSpaceIdRouteImport } from './frontend/routes/app.spaces.$spaceId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './frontend/routes/app.projects.$projectId.index'
import { Route as AppProjectsProjectIdAnalyticsRouteImport } from './frontend/routes/app.projects.$projectId.analytics'
import { Route as AppProjectsProjectIdGrowthRouteImport } from './frontend/routes/app.projects.$projectId.growth'
import { Route as AppProjectsProjectIdKnowledgeRouteImport } from './frontend/routes/app.projects.$projectId.knowledge'
import { Route as AppProjectsProjectIdMasteryRouteImport } from './frontend/routes/app.projects.$projectId.mastery'
import { Route as AppProjectsProjectIdMaterialsRouteImport } from './frontend/routes/app.projects.$projectId.materials'
import { Route as AppProjectsProjectIdQuizRouteImport } from './frontend/routes/app.projects.$projectId.quiz'
import { Route as AppProjectsProjectIdTutorRouteImport } from './frontend/routes/app.projects.$projectId.tutor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesIndexRoute = AppSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesSpaceIdRoute = AppSpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdAnalyticsRoute =
  AppProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdGrowthRoute =
  AppProjectsProjectIdGrowthRouteImport.update({
    id: '/growth',
    path: '/growth',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdKnowledgeRoute =
  AppProjectsProjectIdKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdMasteryRoute =
  AppProjectsProjectIdMasteryRouteImport.update({
    id: '/mastery',
    path: '/mastery',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdMaterialsRoute =
  AppProjectsProjectIdMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdQuizRoute =
  AppProjectsProjectIdQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTutorRoute =
  AppProjectsProjectIdTutorRouteImport.update({
    id: '/tutor',
    path: '/tutor',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/help': typeof AppHelpRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/app/spaces/': typeof AppSpacesIndexRoute
  '/app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/app/projects/$projectId/growth': typeof AppProjectsProjectIdGrowthRoute
  '/app/projects/$projectId/knowledge': typeof AppProjectsProjectIdKnowledgeRoute
  '/app/projects/$projectId/mastery': typeof AppProjectsProjectIdMasteryRoute
  '/app/projects/$projectId/materials': typeof AppProjectsProjectIdMaterialsRoute
  '/app/projects/$projectId/quiz': typeof AppProjectsProjectIdQuizRoute
  '/app/projects/$projectId/tutor': typeof AppProjectsProjectIdTutorRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/help': typeof AppHelpRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/app/spaces': typeof AppSpacesIndexRoute
  '/app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/app/projects/$projectId/growth': typeof AppProjectsProjectIdGrowthRoute
  '/app/projects/$projectId/knowledge': typeof AppProjectsProjectIdKnowledgeRoute
  '/app/projects/$projectId/mastery': typeof AppProjectsProjectIdMasteryRoute
  '/app/projects/$projectId/materials': typeof AppProjectsProjectIdMaterialsRoute
  '/app/projects/$projectId/quiz': typeof AppProjectsProjectIdQuizRoute
  '/app/projects/$projectId/tutor': typeof AppProjectsProjectIdTutorRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/help': typeof AppHelpRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/app/spaces/': typeof AppSpacesIndexRoute
  '/app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/app/projects/$projectId/growth': typeof AppProjectsProjectIdGrowthRoute
  '/app/projects/$projectId/knowledge': typeof AppProjectsProjectIdKnowledgeRoute
  '/app/projects/$projectId/mastery': typeof AppProjectsProjectIdMasteryRoute
  '/app/projects/$projectId/materials': typeof AppProjectsProjectIdMaterialsRoute
  '/app/projects/$projectId/quiz': typeof AppProjectsProjectIdQuizRoute
  '/app/projects/$projectId/tutor': typeof AppProjectsProjectIdTutorRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/activity'
    | '/app/analytics'
    | '/app/help'
    | '/app/settings'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/spaces/$spaceId'
    | '/app/spaces/'
    | '/app/projects/$projectId/analytics'
    | '/app/projects/$projectId/growth'
    | '/app/projects/$projectId/knowledge'
    | '/app/projects/$projectId/mastery'
    | '/app/projects/$projectId/materials'
    | '/app/projects/$projectId/quiz'
    | '/app/projects/$projectId/tutor'
    | '/app/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/app/activity'
    | '/app/analytics'
    | '/app/help'
    | '/app/settings'
    | '/app'
    | '/app/spaces/$spaceId'
    | '/app/spaces'
    | '/app/projects/$projectId/analytics'
    | '/app/projects/$projectId/growth'
    | '/app/projects/$projectId/knowledge'
    | '/app/projects/$projectId/mastery'
    | '/app/projects/$projectId/materials'
    | '/app/projects/$projectId/quiz'
    | '/app/projects/$projectId/tutor'
    | '/app/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/activity'
    | '/app/analytics'
    | '/app/help'
    | '/app/settings'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/spaces/$spaceId'
    | '/app/spaces/'
    | '/app/projects/$projectId/analytics'
    | '/app/projects/$projectId/growth'
    | '/app/projects/$projectId/knowledge'
    | '/app/projects/$projectId/mastery'
    | '/app/projects/$projectId/materials'
    | '/app/projects/$projectId/quiz'
    | '/app/projects/$projectId/tutor'
    | '/app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spaces/': {
      id: '/app/spaces/'
      path: '/spaces'
      fullPath: '/app/spaces/'
      preLoaderRoute: typeof AppSpacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spaces/$spaceId': {
      id: '/app/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/app/spaces/$spaceId'
      preLoaderRoute: typeof AppSpacesSpaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/analytics': {
      id: '/app/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/app/projects/$projectId/analytics'
      preLoaderRoute: typeof AppProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/growth': {
      id: '/app/projects/$projectId/growth'
      path: '/growth'
      fullPath: '/app/projects/$projectId/growth'
      preLoaderRoute: typeof AppProjectsProjectIdGrowthRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/knowledge': {
      id: '/app/projects/$projectId/knowledge'
      path: '/knowledge'
      fullPath: '/app/projects/$projectId/knowledge'
      preLoaderRoute: typeof AppProjectsProjectIdKnowledgeRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/mastery': {
      id: '/app/projects/$projectId/mastery'
      path: '/mastery'
      fullPath: '/app/projects/$projectId/mastery'
      preLoaderRoute: typeof AppProjectsProjectIdMasteryRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/materials': {
      id: '/app/projects/$projectId/materials'
      path: '/materials'
      fullPath: '/app/projects/$projectId/materials'
      preLoaderRoute: typeof AppProjectsProjectIdMaterialsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/quiz': {
      id: '/app/projects/$projectId/quiz'
      path: '/quiz'
      fullPath: '/app/projects/$projectId/quiz'
      preLoaderRoute: typeof AppProjectsProjectIdQuizRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/tutor': {
      id: '/app/projects/$projectId/tutor'
      path: '/tutor'
      fullPath: '/app/projects/$projectId/tutor'
      preLoaderRoute: typeof AppProjectsProjectIdTutorRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdAnalyticsRoute: typeof AppProjectsProjectIdAnalyticsRoute
  AppProjectsProjectIdGrowthRoute: typeof AppProjectsProjectIdGrowthRoute
  AppProjectsProjectIdKnowledgeRoute: typeof AppProjectsProjectIdKnowledgeRoute
  AppProjectsProjectIdMasteryRoute: typeof AppProjectsProjectIdMasteryRoute
  AppProjectsProjectIdMaterialsRoute: typeof AppProjectsProjectIdMaterialsRoute
  AppProjectsProjectIdQuizRoute: typeof AppProjectsProjectIdQuizRoute
  AppProjectsProjectIdTutorRoute: typeof AppProjectsProjectIdTutorRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdAnalyticsRoute: AppProjectsProjectIdAnalyticsRoute,
  AppProjectsProjectIdGrowthRoute: AppProjectsProjectIdGrowthRoute,
  AppProjectsProjectIdKnowledgeRoute: AppProjectsProjectIdKnowledgeRoute,
  AppProjectsProjectIdMasteryRoute: AppProjectsProjectIdMasteryRoute,
  AppProjectsProjectIdMaterialsRoute: AppProjectsProjectIdMaterialsRoute,
  AppProjectsProjectIdQuizRoute: AppProjectsProjectIdQuizRoute,
  AppProjectsProjectIdTutorRoute: AppProjectsProjectIdTutorRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppHelpRoute: typeof AppHelpRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppSpacesSpaceIdRoute: typeof AppSpacesSpaceIdRoute
  AppSpacesIndexRoute: typeof AppSpacesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppHelpRoute: AppHelpRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppSpacesSpaceIdRoute: AppSpacesSpaceIdRoute,
  AppSpacesIndexRoute: AppSpacesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
